### ISSUE TITLE
m71 build fails due to missing file (zslib-eventing)

### ISSUE THREAD

**Issue by ispysoftware** [webrtc-uwp/webrtc-scripts#30]
<pre>
Loading //third_party/idl/tool_build.gni (referenced from //third_party/idl/zsLib-eventing/zslib_eventing_tool.gni:6)
Loading //sdk/windows/BUILD.gn (referenced from //third_party/idl/BUILD.gn:19)
ERROR at //third_party/idl/zsLib-eventing/zslib_eventing_tool.gni:6:1: Can't load input file.
import("//third_party/idl/tool_build.gni")
^----------------------------------------
<b>Unable to load:
  D:/webrtcuwp/webrtc-uwp-sdk/webrtc/xplatform/webrtc/third_party/idl/tool_build.gni</b>
I also checked in the secondary tree for:
  D:/webrtcuwp/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/secondary/third_party/idl/tool_build.gni
See //third_party/idl/zsLib/BUILD.gn:5:1: whence it was imported.
import("//third_party/idl/zsLib-eventing/zslib_eventing_tool.gni")
^----------------------------------------------------------------
See //third_party/idl/BUILD.gn:17:7: which caused the file to be included.
      "zsLib:zslib",
      ^------------
</pre>

**Comment by robin-raymond** [comment]
What branch are you on?

**Comment by ispysoftware** [comment]
m71

**Comment by robin-raymond** [comment]
I wonder if there's a D: drive script bug. Have you tried it on the C: drive? It might be some of the setup scripts have a glitch and are incorrectly assuming C: and thus making this issue.

I assume you've recursively cloned the repo and are building from the .sln file?

**Comment by ispysoftware** [comment]
I haven't tried it from the C drive, master was building fine. I've cloned the repo and am building from the .sln file - same issue running python run.py - i can't find tool_build.gni anywhere in the source tree

**Comment by robin-raymond** [comment]
`git clone --recursive https://github.com/webrtc-uwp/webrtc-uwp-sdk.git -b releases/m71`

^ I want to be certain you've done a recursive clone as I see it on the branch:

https://github.com/webrtc-uwp/templates/tree/345bac675ddc01f47bc7cd7e1e71e5362b194131/gn

Do you have a folder:
`D:/webrtcuwp/webrtc-uwp-sdk/webrtc/xplatform/templates/'

**Comment by ispysoftware** [comment]
i'll start over with it - i'd done a master clone and then a branch/ merge and a submodule recursive update. I've got that folder but am missing the tool_build.gni file - thanks for that, i couldn't find it. I'll let you know how it goes. Thanks a lot for responding so fast.

**Comment by robin-raymond** [comment]
Np. I'll leave the issue open until you confirm it's okay.

**Comment by ispysoftware** [comment]
That did it, thanks! Not sure why it didn't pick those files up from git.

**Comment by ispysoftware** [comment]
Hey Robin, thanks for your help with that. I'm trying to add some code into
the wrapper so I can create dummy audio and video tracks and push audio and
video frames through from code. The audio and video i'm getting from
network IP cameras so there are no physical devices on the computer. To be
honest I am completely out of my depth with the webrtc wrapper code. I
managed to get an older version of the webrtc framework doing what I wanted
and its been working for a couple of years now but I don't really know what
I'm doing with this IDL and code generation process and I feel a bit like a
monkey with a hammer let loose on a Ferrari.

Basically I want to be able to create new devices like:

var videoTrackSource = VideoTrackSource.Create(null, mediaConstraints);
//setup frame size/ encoding etc
var localVideoTrack = MediaStreamTrack.CreateVideoTrack("SELF_VIDEO",
videoTrackSource);

and

AudioOptions audioOptions = new AudioOptions();
//setup samples/ channels etc
var audioTrackSource = AudioTrackSource.Create(audioOptions);
var localAudioTrack = MediaStreamTrack.CreateAudioTrack("SELF_AUDIO",
audioTrackSource);

then something like (from managed code):

localVideoTrack.PushFrame(pointerToEncodedFrame, length);
localAudioTrack.PushFrame(pointerToRawAudio, length);

Do you have any plans to add anything like this in any time soon?  If not
am I on the right track with this approach?

Thanks man.

Sean
